server:
  port: ${PORT}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS}

gemini:
  api:
    key: ${GEMINI_API_KEY}
    version: ${GEMINI_API_VERSION}
  model: ${GEMINI_MODEL}
  max:
    output:
      tokens: ${GEMINI_MAX_OUTPUT_TOKENS}
  temperature: ${GEMINI_TEMPERATURE}
  top:
    p: ${GEMINI_TOP_P}
  system:
    instruction: ${GEMINI_SYSTEM_INSTRUCTION}
  timeout:
    ms: ${GEMINI_TIMEOUT_MS}

logging:
  level:
    root: WARN
